### ISSUE TITLE
Use a hierarchical config format

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-cloud-client#426]
We could switch from Python's config INI format to YAML (or JSON), enabling easy nesting of options.

For example:
```
client: qpu
solver:
  num_active_qubits:
    gt: 4000
  topology:
    type: pegasus
```

This would enable a partial update (`PATCH` with a diff), e.g:
```
solver:
  topology:
    type: chimera
```
